
package br.com.viavarejo.reversa.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.xml.bind.annotation.XmlSeeAlso;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "logisticaReversaWS", targetNamespace = "http://service.logisticareversa.correios.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogisticaReversaWS {


    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param coletasSolicitadas
     * @param codigoServico
     * @param destinatario
     * @return
     *     returns br.com.RetornoPostagem
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "solicitarPostagemReversa", targetNamespace = "")
    @RequestWrapper(localName = "solicitarPostagemReversa", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SolicitarPostagemReversa")
    @ResponseWrapper(localName = "solicitarPostagemReversaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SolicitarPostagemReversaResponse")
    public RetornoPostagem solicitarPostagemReversa(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "destinatario", targetNamespace = "")
                Pessoa destinatario,
        @WebParam(name = "coletas_solicitadas", targetNamespace = "")
        List<ColetaReversa> coletasSolicitadas)
        throws ComponenteException
    ;

    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param codigoServico
     * @param cepDestinatario
     * @param coleta
     * @return
     *     returns br.com.RetornoValidacao
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "validarPostagemSimultanea", targetNamespace = "")
    @RequestWrapper(localName = "validarPostagemSimultanea", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.ValidarPostagemSimultanea")
    @ResponseWrapper(localName = "validarPostagemSimultaneaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.ValidarPostagemSimultaneaResponse")
    public RetornoValidacao validarPostagemSimultanea(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "cep_destinatario", targetNamespace = "")
        String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        ColetaSimultanea coleta)
        throws ComponenteException
    ;

    /**
     * 
     * @param tipo
     * @param codAdministrativo
     * @param numeroPedido
     * @return
     *     returns br.com.RetornoCancelamento
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "cancelarPedido", targetNamespace = "")
    @RequestWrapper(localName = "cancelarPedido", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.CancelarPedido")
    @ResponseWrapper(localName = "cancelarPedidoResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.CancelarPedidoResponse")
    public RetornoCancelamento cancelarPedido(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "numeroPedido", targetNamespace = "")
        String numeroPedido,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo)
        throws ComponenteException
    ;

    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param coletasSolicitadas
     * @param codigoServico
     * @param destinatario
     * @return
     *     returns br.com.RetornoPostagem
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "solicitarPostagemSimultanea", targetNamespace = "")
    @RequestWrapper(localName = "solicitarPostagemSimultanea", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SolicitarPostagemSimultanea")
    @ResponseWrapper(localName = "solicitarPostagemSimultaneaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SolicitarPostagemSimultaneaResponse")
    public RetornoPostagem solicitarPostagemSimultanea(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "destinatario", targetNamespace = "")
        Pessoa destinatario,
        @WebParam(name = "coletas_solicitadas", targetNamespace = "")
        List<ColetaSimultanea> coletasSolicitadas)
        throws ComponenteException
    ;

    /**
     * 
     * @param tipo
     * @param codAdministrativo
     * @param servico
     * @param quantidade
     * @return
     *     returns br.com.RetornoFaixaNumerica
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "solicitarRange", targetNamespace = "")
    @RequestWrapper(localName = "solicitarRange", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SolicitarRange")
    @ResponseWrapper(localName = "solicitarRangeResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SolicitarRangeResponse")
    public RetornoFaixaNumerica solicitarRange(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "servico", targetNamespace = "")
        String servico,
        @WebParam(name = "quantidade", targetNamespace = "")
        String quantidade)
        throws ComponenteException
    ;

    /**
     * 
     * @param codAdministrativo
     * @param data
     * @param tipoSolicitacao
     * @return
     *     returns br.com.RetornoAcompanhamento
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "acompanharPedidoPorData", targetNamespace = "")
    @RequestWrapper(localName = "acompanharPedidoPorData", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.AcompanharPedidoPorData")
    @ResponseWrapper(localName = "acompanharPedidoPorDataResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.AcompanharPedidoPorDataResponse")
    public RetornoAcompanhamento acompanharPedidoPorData(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "tipoSolicitacao", targetNamespace = "")
        String tipoSolicitacao,
        @WebParam(name = "data", targetNamespace = "")
        String data)
        throws ComponenteException
    ;

    /**
     * 
     * @param codigoObjeto
     * @return
     *     returns br.com.RetornoResumoColeta
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "consultarResumoColeta", targetNamespace = "")
    @RequestWrapper(localName = "consultarResumoColeta", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.ConsultarResumoColeta")
    @ResponseWrapper(localName = "consultarResumoColetaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.ConsultarResumoColetaResponse")
    public RetornoResumoColeta consultarResumoColeta(
        @WebParam(name = "codigoObjeto", targetNamespace = "")
        String codigoObjeto)
        throws ComponenteException
    ;

    /**
     * 
     * @param tipoBusca
     * @param codAdministrativo
     * @param tipoSolicitacao
     * @param numeroPedido
     * @return
     *     returns br.com.RetornoAcompanhamento
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "acompanharPedido", targetNamespace = "")
    @RequestWrapper(localName = "acompanharPedido", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.AcompanharPedido")
    @ResponseWrapper(localName = "acompanharPedidoResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.AcompanharPedidoResponse")
    public RetornoAcompanhamento acompanharPedido(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "tipoBusca", targetNamespace = "")
        String tipoBusca,
        @WebParam(name = "tipoSolicitacao", targetNamespace = "")
        String tipoSolicitacao,
        @WebParam(name = "numeroPedido", targetNamespace = "")
        List<String> numeroPedido)
        throws ComponenteException
    ;

    /**
     * 
     * @param codAdministrativo
     * @param qtdeDias
     * @param numeroPedido
     * @return
     *     returns br.com.RetornoRevalidarPrazo
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "revalidarPrazoAutorizacaoPostagem", targetNamespace = "")
    @RequestWrapper(localName = "revalidarPrazoAutorizacaoPostagem", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.RevalidarPrazoAutorizacaoPostagem")
    @ResponseWrapper(localName = "revalidarPrazoAutorizacaoPostagemResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.RevalidarPrazoAutorizacaoPostagemResponse")
    public RetornoRevalidarPrazo revalidarPrazoAutorizacaoPostagem(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "numeroPedido", targetNamespace = "")
        String numeroPedido,
        @WebParam(name = "qtdeDias", targetNamespace = "")
        String qtdeDias)
        throws ComponenteException
    ;

    /**
     * 
     * @return
     *     returns br.com.RetornoSobreWebService
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "sobreWebService", targetNamespace = "")
    @RequestWrapper(localName = "sobreWebService", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SobreWebService")
    @ResponseWrapper(localName = "sobreWebServiceResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.SobreWebServiceResponse")
    public RetornoSobreWebService sobreWebService()
        throws ComponenteException
    ;

    /**
     * 
     * @param cartao
     * @param codAdministrativo
     * @param codigoServico
     * @param cepDestinatario
     * @param coleta
     * @return
     *     returns br.com.RetornoValidacao
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "validarPostagemReversa", targetNamespace = "")
    @RequestWrapper(localName = "validarPostagemReversa", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.ValidarPostagemReversa")
    @ResponseWrapper(localName = "validarPostagemReversaResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.ValidarPostagemReversaResponse")
    public RetornoValidacao validarPostagemReversa(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        String codAdministrativo,
        @WebParam(name = "codigo_servico", targetNamespace = "")
        String codigoServico,
        @WebParam(name = "cartao", targetNamespace = "")
        String cartao,
        @WebParam(name = "cep_destinatario", targetNamespace = "")
        String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        ColetaReversa coleta)
        throws ComponenteException
    ;

    /**
     * 
     * @param numero
     * @return
     *     returns br.com.RetornoDigitoVerificador
     * @throws ComponenteException
     */
    @WebMethod
    @WebResult(name = "calcularDigitoVerificador", targetNamespace = "")
    @RequestWrapper(localName = "calcularDigitoVerificador", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.CalcularDigitoVerificador")
    @ResponseWrapper(localName = "calcularDigitoVerificadorResponse", targetNamespace = "http://service.logisticareversa.correios.com.br/", className = "br.com.CalcularDigitoVerificadorResponse")
    public RetornoDigitoVerificador calcularDigitoVerificador(
        @WebParam(name = "numero", targetNamespace = "")
        String numero)
        throws ComponenteException
    ;

}
